const actionTypes = {
    LOAD_ORGANIZATIONS_DATA_SUCCESS: 'LOAD_ORGANIZATIONS_DATA_SUCCESS',
    LOAD_ORGANIZATIONS_DATA_FAIL: 'LOAD_ORGANIZATIONS_DATA_FAIL',
    LOAD_ORGANIZATION_DATA_SUCCESS: 'LOAD_ORGANIZATION_DATA_SUCCESS',
    LOAD_ORGANIZATION_DATA_FAIL: 'LOAD_ORGANIZATION_DATA_FAIL'
};
export default actionTypes;